import { useState, useEffect } from 'react';
import { adminAPI } from '../../services/api';

const GeneratedDocs = () => {
    const [docs, setDocs] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadDocs();
    }, []);

    const loadDocs = async () => {
        try {
            setLoading(true);
            const res = await adminAPI.getGeneratedDocs();
            setDocs(res.data.docs || []);
        } catch (error) {
            console.error('Failed to load generated docs', error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-64">
                <div className="w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
            </div>
        );
    }

    return (
        <div>
            <h1 className="text-3xl font-bold text-gray-800 mb-6">Generated Documents</h1>
            <p className="text-gray-600 mb-6">View all legal documents generated by business users.</p>

            <div className="bg-white rounded-xl shadow-md overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-100">
                    <h3 className="font-bold text-gray-800">Document Log</h3>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-gray-50 border-b border-gray-200 text-xs uppercase tracking-wider text-gray-500">
                                <th className="p-4 font-medium">Date</th>
                                <th className="p-4 font-medium">User</th>
                                <th className="p-4 font-medium">Template Type</th>
                                <th className="p-4 font-medium text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {docs.map((doc) => (
                                <tr key={doc._id} className="hover:bg-gray-50">
                                    <td className="p-4 whitespace-nowrap text-sm text-gray-600">
                                        {new Date(doc.generatedAt).toLocaleString()}
                                    </td>
                                    <td className="p-4 whitespace-nowrap">
                                        <p className="font-semibold text-gray-800">{doc.userId?.name || 'Unknown'}</p>
                                        <p className="text-xs text-gray-500">{doc.userId?.email}</p>
                                    </td>
                                    <td className="p-4 whitespace-nowrap">
                                        <span className="bg-indigo-100 text-indigo-800 text-xs px-3 py-1 rounded-full font-medium">
                                            {doc.templateId?.templateName || doc.templateId?.type || 'Standard Agreement'}
                                        </span>
                                    </td>
                                    <td className="p-4 text-right">
                                        {doc.documentUrl ? (
                                            <a
                                                href={doc.documentUrl}
                                                target="_blank"
                                                rel="noreferrer"
                                                className="text-indigo-600 hover:text-indigo-900 text-sm font-medium"
                                            >
                                                Download &rarr;
                                            </a>
                                        ) : (
                                            <span className="text-gray-400 text-sm">N/A</span>
                                        )}
                                    </td>
                                </tr>
                            ))}
                            {docs.length === 0 && (
                                <tr>
                                    <td colSpan="4" className="p-8 text-center text-gray-500">
                                        No documents generated yet.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default GeneratedDocs;
